version: "3.9"

services:
  pizzeria_app:
    container_name: pizzeria
    image: group40/pizzeria:v1
    build: .
    depends_on:
      - mongo
    ports:
      - "4500:4500"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - mongo

  nginx:
    container_name: nginx-c
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - backend
      - frontend
    depends_on:
      - pizzeria_app


volumes:
  mongodata:

networks:
  frontend:
  backend:
    internal: true