version: "3.9"
name: pizzeria
services:
  pizzeria-app:
    container_name: pizzeria-app
    image: group40/pizzeria:v1
    build: .
    depends_on:
      - mongo
    ports:
      - "4500:4500"
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_user
      MONGO_INITDB_ROOT_PASSWORD: app_password
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: app_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: app_password
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - mongo
    restart: unless-stopped

  nginx:
    container_name: nginx-proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./services/nginx/certs/localhost.key:/etc/ssl/private/localhost.key
    networks:
      - backend
      - frontend
    depends_on:
      - pizzeria-app

volumes:
  mongodata:

networks:
  frontend:
  backend: